server:
  port: 8888
spring:
  application:
    name: oauth
  #datasource:
   # type: com.zaxxer.hikari.HikariDataSource
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # jdbc-url: jdbc:mysql://localhost:3306/secondhandshop?serverTimezone=UTC&characterEncoding=utf-8
    #  username: root
  #  password: 8235250